name: angularprime_dart
version: 0.0.1

transformers:
- $dart2js:
    checked: true
    minify: false

dependencies:
  angular: 0.12.0
  js: any
  shadow_dom: any
  animation: any


dev_dependencies:
  unittest: any

